# simple.gocd.yaml
pipelines:
  demo:
    group: demo
    materials:
      svn:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/elzinko/demo.git
    stages:
      - build: # name of stage
          jobs:
            docker-version: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: docker version 
