version: '2'
services:
  demo:
    image: 518620812774.dkr.ecr.eu-west-1.amazonaws.com/demo:1.0
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
